### ISSUE TITLE
error compile

### ISSUE THREAD

**Issue by syare234** [oforpertainingtothesun/xmr-stak-sparc#1]
Dear sir

i get error

this message error

[ 90%] Building CXX object CMakeFiles/xmr-stak-cpp.dir/crypto/cryptonight_sparc.cpp.o
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 27: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 32: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 39: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 48: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 53: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 60: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 69: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 72: error: cannot use SPARC4 instructions in a non-SPARC4 target binary
/usr/bin/as: "/var/tmp//ccqmaiYr.s", line 81: error: cannot use SPARC4 instructions in a non-SPARC4 target binary

i use Ldom oracle sparc T5-2

**Comment by oforpertainingtothesun** [comment]
Can you run in verbose and get the processor flag information for me:

```
make VERBOSE=1
isainfo -v
```
and attach the output?

It could be that the LDOM is a generic LDOM or in migration-ready mode which means that the OS won't understand T4-1 instructions.

You could also try replacing "-mtune=native -mcpu=native" in the CMakeLists.txt file with:

"-mtune=niagara4 -mcpu=niagara4"

If the resulting binaries give an illegal instruction it means that the crypto instructions are not enabled in the LDOM - but you could run the binaries elsewhere.

**Comment by syare234** [comment]
Dear sir

i was replace  "-mtune=native -mcpu=native" in the CMakeLists.txt file with:

"-mtune=niagara4 -mcpu=niagara4"



and i got error : 

[ 95%] Building CXX object CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
Linking CXX executable bin/gtest
Undefined                    first referenced
 symbol                             in file
std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream() CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::begin() /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__throw_out_of_range_fmt(char const*, ...) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_local_data() /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long) const /usr/local/lib/libgtest.a(gtest-all.cc.o)
vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> > CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::substr(unsigned long, unsigned long) const /usr/local/lib/libgtest.a(gtest-all.cc.o)
VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> > CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char const*, char const*) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::str() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose() /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string() /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::erase(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*, unsigned long) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char const*) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream() CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_set_length(unsigned long) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long) const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::end() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider(char*, std::allocator<char> const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_capacity(unsigned long) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::begin() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data(char*) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::end() /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::data() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/local/lib/libgtest.a(gtest-all.cc.o)
vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> > CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_data() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(unsigned long, char) /usr/local/lib/libgtest.a(gtest-all.cc.o)
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) CMakeFiles/gtest.dir/test/googletest_correct.cpp.o
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::length() const /usr/local/lib/libgtest.a(gtest-all.cc.o)
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
gmake[2]: *** [bin/gtest] Error 1
gmake[1]: *** [CMakeFiles/gtest.dir/all] Error 2



= this my isainfo -v

root@solaris-11:~/builds# isainfo -v
64-bit sparcv9 applications
        crc32c cbcond pause mont mpmul sha512 sha256 sha1 md5 camellia kasumi
        des aes ima hpc vis3 fmaf asi_blk_init vis2 vis popc
32-bit sparc applications
        crc32c cbcond pause mont mpmul sha512 sha256 sha1 md5 camellia kasumi
        des aes ima hpc vis3 fmaf asi_blk_init vis2 vis popc v8plus div32 mul32

**Comment by oforpertainingtothesun** [comment]
Good news! You should have an xmr-stak executable - although the google tests have failed. You should be able to run this if you tailor the configuration file in the repository. I think perhaps gcc is not picking up the isainfo correctly and doesn't know you have the aes extensions. Can you check whether the xmr-stak executable runs?

For gtest I think you may have a version of gtest build with the older compiler. See this answer:
https://stackoverflow.com/questions/33394934/converting-std-cxx11string-to-stdstring

A workaround is to add:
`add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0)`

to the CMakeLists.txt file. That will use the old ABI and the __cxx11 symbols won't be used.

Alternatively, rebuild gtest making sure that you have this environment before running cmake:
```
CC=/usr/gcc/5.5/bin/gcc
CXX=/usr/gcc/5.5/bin/g++
CFLAGS=-m64
export CC CXX CFLAGS
```
that will ensure there is no way that the old compiler can get picked up.

**Comment by syare234** [comment]
dear sir

i was success compile xmr-stak,after i run, i have problem

[2018-02-09 17:28:21] : Result rejected by the pool.
[2018-02-09 17:28:30] : New block detected.
[2018-02-09 17:28:40] : Result rejected by the pool.
[2018-02-09 17:29:13] : Result rejected by the pool.
[2018-02-09 17:29:15] : Result rejected by the pool.


why this rejected by the pool

**Comment by oforpertainingtothesun** [comment]
If you hit "r" it should give you a break down of the results which contains the reason for failure. If its a "low difficulty" error - than means that the calculations have not run correctly. There should not be significant differences between your T5 and my T4 to cause this though, so I'll test here and see if I can pin this down.

**Comment by oforpertainingtothesun** [comment]
I've just found that low power mode doesn't work. Can you check/change your config so that low_power_mode is set to false please? I'll fix this ASAP in the meantime.

**Comment by oforpertainingtothesun** [comment]
I've just confirmed that low_power_mode set to true results in rejected results but set to false the results get accepted. I've created a new issue to fix that - so if you get the same results we can shut this issue down.

**Comment by syare234** [comment]
Thanks sir
It's work
